# Generated by Django 3.1.1 on 2025-01-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.CharField(default='5001', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='06000007', max_length=15),
        ),
    ]
