# Generated by Django 3.1.1 on 2025-01-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20250113_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(default='5001', max_length=14),
        ),
    ]
