# Generated by Django 3.1.1 on 2025-01-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20250114_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='niveau',
            field=models.CharField(choices=[('3eme année', '3ème année'), ('4eme année', '4ème année'), ('5eme année', '5ème année'), ('6eme année', '6ème année')], default='3eme année', max_length=20),
        ),
    ]
