# Generated by Django 3.1.1 on 2025-01-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_student_niveau'),
        ('main_app', '0006_auto_20250114_1421'),
    ]

    operations = [
    ]
