# Generated by Django 3.1.1 on 2025-01-16 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20250114_2341'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='attendance',
            name='time_from',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_to',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
    ]
