# Generated by Django 3.1.1 on 2025-01-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20250114_2341'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='course',
            name='niveau',
            field=models.CharField(choices=[('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année')], default='3ème année', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='niveau',
            field=models.CharField(choices=[('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année')], default='3ème année', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
    ]
