# Generated by Django 3.1.1 on 2025-01-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20250115_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(default='Default Session', on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.session'),
        ),
    ]
