# Generated by Django 3.1.1 on 2025-01-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20250116_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='niveau',
            field=models.CharField(choices=[('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année')], default='5ème année', max_length=20),
        ),
    ]
