# Generated by Django 3.1.1 on 2025-01-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20250116_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='niveau',
        ),
        migrations.AlterField(
            model_name='subject',
            name='niveau',
            field=models.CharField(choices=[('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année')], default='3ème année', max_length=20),
        ),
    ]
