# Generated by Django 3.1.1 on 2025-01-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20250117_0006'),
        ('main_app', '0019_remove_course_description'),
    ]

    operations = [
    ]
