# Generated by Django 3.1.1 on 2025-01-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_merge_20250117_1823'),
        ('main_app', '0022_absence'),
    ]

    operations = [
    ]
