# Generated by Django 3.1.1 on 2025-01-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_merge_20250119_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='dateN',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lieu',
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.session'),
        ),
    ]
