# Generated by Django 3.1.1 on 2025-01-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20250119_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateN',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lieu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
