# Generated by Django 3.1.1 on 2025-01-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20250119_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationstudent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notifications/'),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/images/'),
        ),
    ]
