# Generated by Django 3.1.1 on 2025-01-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20250120_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationstudent',
            name='image',
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20),
        ),
    ]
