# Generated by Django 3.1.1 on 2025-01-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20250120_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationstudent',
            old_name='file',
            new_name='files',
        ),
    ]
