# Generated by Django 3.1.1 on 2025-01-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20250120_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstudent',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('success', 'Envoyée'), ('failed', 'Échouée')], default='pending', max_length=20),
        ),
    ]
