# Generated by Django 3.1.1 on 2025-01-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20250121_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationstudent',
            name='files',
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notifications/'),
        ),
    ]
