# Generated by Django 3.1.1 on 2025-01-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20250121_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fcm_token',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
