# Generated by Django 3.1.1 on 2025-01-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20250121_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
