# Generated by Django 5.1.1 on 2025-01-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_suivicours_emploitemps'),
        ('main_app', '0033_auto_20250121_1422'),
    ]

    operations = [
    ]
