# Generated by Django 3.1.1 on 2025-01-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_merge_20250121_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploitemps',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='emploitemps',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='suivicours',
            name='heures_totales',
        ),
        migrations.RemoveField(
            model_name='suivicours',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='suivicours',
            name='professeur',
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='horaire',
            field=models.CharField(choices=[('08:00-10:00', '08:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('08:00-12:00', '08:00-12:00'), ('14:00-18:00', '14:00-18:00')], default='08:00-10:00', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationstaff',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='staff_notifications/'),
        ),
        migrations.AddField(
            model_name='suivicours',
            name='total_heures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], default='Lundi', max_length=10),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_temps', to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='notificationstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suivicours',
            name='heures_effectuees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suivicours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='main_app.subject'),
        ),
    ]
