# Generated by Django 5.1.1 on 2025-01-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_merge_20250121_1608'),
    ]

    operations = [
        
      
       
       
        migrations.AddField(
            model_name='emploitemps',
            name='horaire',
            field=models.CharField(choices=[('08:00-10:00', '08:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('08:00-12:00', '08:00-12:00'), ('14:00-18:00', '14:00-18:00')], default='08:00-10:00', max_length=20),
        ),
        migrations.AddField(
            model_name='suivicours',
            name='total_heures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], default='Lundi', max_length=10),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_temps', to='main_app.student'),
        ),
        migrations.AlterField(
            model_name='suivicours',
            name='heures_effectuees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suivicours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='main_app.subject'),
        ),
    ]
