# Generated by Django 3.1.1 on 2025-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_auto_20250121_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationstaff',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notifications_staff'),
        ),
    ]
