# Generated by Django 5.1.1 on 2025-01-21 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_alter_emploitemps_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitemps',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
    ]
