# Generated by Django 3.1.1 on 2025-01-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_auto_20250121_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstaff',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='staff_notifications'),
        ),
    ]
