# Generated by Django 5.1.1 on 2025-01-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_alter_emploitemps_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploitemps',
            name='suivi',
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='progression',
            field=models.CharField(blank=True, help_text="Décrivez la progression, par exemple '50% terminé' ou 'Chapitre 3 terminé'.", max_length=255, null=True),
        ),
    ]
