# Generated by Django 5.1.1 on 2025-01-21 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_remove_emploitemps_suivi_emploitemps_progression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploitemps',
            name='jour',
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
