# Generated by Django 5.1.1 on 2025-01-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20250121_2143'),
        ('main_app', '0040_emploitemps_jour'),
    ]

    operations = [
    ]
