# Generated by Django 5.1.1 on 2025-01-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_merge_0037_auto_20250121_2143_0040_emploitemps_jour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploitemps',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='emploitemps',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='suivicours',
            name='heures_totales',
        ),
    ]
