# Generated by Django 5.1.1 on 2025-01-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_remove_emploitemps_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivicours',
            name='niveau',
        ),
    ]
