# Generated by Django 5.1.1 on 2025-01-21 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_remove_suivicours_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitemps',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_temps', to='main_app.student'),
        ),
    ]
