# Generated by Django 3.1.1 on 2025-01-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_alter_emploitemps_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitemps',
            name='niveau',
            field=models.CharField(choices=[('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année')], default='3ème année', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
