# Generated by Django 5.1.1 on 2025-01-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_auto_20250122_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='course',
        ),
    ]
