# Generated by Django 5.1.1 on 2025-01-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_remove_staff_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AlterField(
            model_name='subject',
            name='niveau',
            field=models.CharField(choices=[('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année'), ('6ème année', '6ème année')], default='3ème année', max_length=20),
        ),
    ]
