# Generated by Django 3.1.1 on 2025-01-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_subject_volume_horaire_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_evenement', models.CharField(choices=[('FERIE', 'Jour férié'), ('EXAMEN_PARTIEL', 'Examen partiel'), ('EXAMEN_FINAL', 'Examen final')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('niveau', models.CharField(choices=[('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année'), ('TOUS', 'Tous les niveaux')], default='TOUS', max_length=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
