# Generated by Django 3.1.1 on 2025-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0049_evenementspecial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvenementSpecial',
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='titre_evenement',
            field=models.CharField(blank=True, help_text='Nom du jour férié ou type de vacances', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='type_evenement',
            field=models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN_PARTIEL', 'Examen Partiel'), ('EXAMEN_FINAL', 'Examen Final'), ('JOUR_FERIE', 'Jour Férié'), ('VACANCES', 'Vacances')], default='COURS', max_length=20),
        ),
    ]
