# Generated by Django 3.1.1 on 2025-01-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0050_auto_20250123_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitemps',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.subject'),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.staff'),
        ),
    ]
