# Generated by Django 5.1.1 on 2025-01-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_auto_20250123_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='progression_cours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='volume_horaire_restant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
