# Generated by Django 5.1.1 on 2025-01-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_subject_progression_cours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='volume_horaire_restant',
        ),
        migrations.AddField(
            model_name='subject',
            name='heures_ajoutees',
            field=models.IntegerField(default=0),
        ),
    ]
