# Generated by Django 5.1.1 on 2025-01-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_alter_subject_heures_ajoutees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='heures_ajoutees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='volume_horaire_restant',
            field=models.IntegerField(blank=True, default=40, null=True),
        ),
    ]
