# Generated by Django 5.1.1 on 2025-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_alter_subject_heures_ajoutees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='heures_ajoutees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
