# Generated by Django 3.1.1 on 2025-01-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_alter_subject_heures_ajoutees'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploitemps',
            name='numero_seance',
            field=models.IntegerField(default=0),
        ),
    ]
