# Generated by Django 3.1.1 on 2025-01-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0058_emploitemps_numero_seance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitemps',
            name='titre_evenement',
            field=models.CharField(blank=True, help_text="Titre de l'événement (conférence, tournée, etc.)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='type_evenement',
            field=models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN_PARTIEL', 'Examen Partiel'), ('EXAMEN_FINAL', 'Examen Final'), ('RATTRAPAGE', 'Rattrapage'), ('FORMATION_MILITAIRE', 'Formation Militaire'), ('TOURNEE', 'Tournée'), ('SORTIE', 'Sortie'), ('PROJET', 'Projet'), ('VISITE_MILITAIRE', 'Visite Militaire'), ('CONFERENCE', 'Conférence'), ('JOUR_FERIE', 'Jour Férié'), ('VACANCES', 'Vacances')], default='COURS', max_length=20),
        ),
    ]
