# Generated by Django 3.1.1 on 2025-01-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0061_auto_20250126_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='horaire',
            field=models.CharField(choices=[('08:00-10:00', '08:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('08:00-12:00', '08:00-12:00'), ('14:00-18:00', '14:00-18:00')], default='08:00-10:00', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='emploitemps',
            unique_together={('date', 'horaire', 'niveau')},
        ),
    ]
