# Generated by Django 5.1.1 on 2025-01-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0062_alter_attendancereport_updated_at_and_more'),
        ('main_app', '0062_auto_20250126_2030'),
    ]

    operations = [
    ]
