# Generated by Django 3.1.1 on 2025-01-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0063_merge_20250128_1544'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emploitemps',
            unique_together=set(),
        ),
    ]
