# Generated by Django 3.1.1 on 2025-01-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0064_auto_20250128_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitemps',
            name='horaire',
            field=models.CharField(blank=True, choices=[('08:00-10:00', '08:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('08:00-12:00', '08:00-12:00'), ('14:00-18:00', '14:00-18:00')], default='08:00-10:00', max_length=20, null=True),
        ),
    ]
