# Generated by Django 5.1.1 on 2025-01-30 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0065_auto_20250129_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True, verbose_name="Date de début de l'année académique")),
                ('end_date', models.DateField(unique=True, verbose_name="Date de fin de l'année académique")),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date du jour férié')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True, verbose_name='Date de début des vacances')),
                ('end_date', models.DateField(unique=True, verbose_name='Date de fin des vacances')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Vacances',
                'verbose_name_plural': 'Vacances',
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnel'},
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='niveau',
            field=models.CharField(choices=[('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année'), ('6ème année', '6ème année')], default='3ème année', max_length=20),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='type_evenement',
            field=models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN_PARTIEL', 'Examen Partiel'), ('EXAMEN_FINAL', 'Examen Final'), ('RATTRAPAGE', 'Rattrapage'), ('FORMATION_MILITAIRE', 'Formation Militaire'), ('TOURNEE', 'Tournée'), ('SORTIE', 'Sortie'), ('PROJET', 'Projet'), ('VISITE_MILITAIRE', 'Visite Militaire'), ('CONFERENCE', 'Conférence')], default='COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='heures_ajoutees',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Heures ajoutées'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom de la matière'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='niveau',
            field=models.CharField(choices=[('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année'), ('6ème année', '6ème année')], default='3ème année', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='progression_cours',
            field=models.IntegerField(default=0, verbose_name='Progression du cours en %'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.staff', verbose_name='Professeur'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='volume_horaire_restant',
            field=models.IntegerField(blank=True, default=40, null=True, verbose_name='Volume horaire restant'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='volume_horaire_total',
            field=models.IntegerField(default=40, verbose_name='Volume horaire total'),
        ),
    ]
