# Generated by Django 3.1.1 on 2025-02-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0066_academicyear_holiday_vacation_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploitemps',
            name='duree',
            field=models.IntegerField(choices=[(1, '1 heure'), (2, '2 heures'), (3, '3 heures'), (4, '4 heures')], default=2, verbose_name='Durée (en heures)'),
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='heure_debut',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], default='08:00', max_length=5, verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Femelle')], max_length=1),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='horaire',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
