# Generated by Django 3.1.1 on 2025-02-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0067_auto_20250203_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploitemps',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='duree',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='horaire',
            field=models.CharField(blank=True, choices=[('08:00-10:00', '08:00-10:00'), ('08:00-11:00', '08:00-11:00'), ('08:00-12:00', '08:00-12:00'), ('10:00-12:00', '10:00-12:00'), ('10:00-13:00', '10:00-13:00'), ('14:00-16:00', '14:00-16:00'), ('14:00-17:00', '14:00-17:00'), ('14:00-18:00', '14:00-18:00'), ('16:00-18:00', '16:00-18:00'), ('16:00-19:00', '16:00-19:00')], default='08:00-10:00', max_length=20, null=True),
        ),
    ]
