# Generated by Django 3.1.1 on 2025-02-03 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0068_auto_20250203_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploitemps',
            name='duree_minutes',
            field=models.IntegerField(default=120, validators=[django.core.validators.MinValueValidator(30, 'La durée minimale est de 30 minutes'), django.core.validators.MaxValueValidator(480, 'La durée maximale est de 8 heures')], verbose_name='Durée (en minutes)'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
