# Generated by Django 3.1.1 on 2025-02-03 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_add_duration_to_emploitemps'),
        ('main_app', '0069_auto_20250203_1705'),
    ]

    operations = [
    ]
