# Generated by Django 3.1.1 on 2025-02-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0070_merge_20250204_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploitemps',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='emploitemps',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='emploitemps',
            name='duree_minutes',
        ),
        migrations.RemoveField(
            model_name='emploitemps',
            name='horaire',
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
