# Generated by Django 5.1.1 on 2025-02-09 14:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0071_auto_20250204_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option5eme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('GRN', 'GRN'), ('VALO', 'VALO'), ('AF', 'AF'), ('ECO', 'ECO'), ('EF', 'EF'), ('GAP', 'GAP')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploiTempsOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], default='Lundi', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('progression', models.CharField(blank=True, help_text="Décrivez la progression, par exemple '50% terminé' ou 'Chapitre 3 terminé'.", max_length=255, null=True)),
                ('type_evenement', models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN_PARTIEL', 'Examen Partiel'), ('EXAMEN_FINAL', 'Examen Final'), ('RATTRAPAGE', 'Rattrapage'), ('FORMATION_MILITAIRE', 'Formation Militaire'), ('TOURNEE', 'Tournée'), ('SORTIE', 'Sortie'), ('PROJET', 'Projet'), ('VISITE_MILITAIRE', 'Visite Militaire'), ('CONFERENCE', 'Conférence')], default='COURS', max_length=20)),
                ('titre_evenement', models.CharField(blank=True, help_text="Titre de l'événement (conférence, tournée, etc.)", max_length=255, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('numero_seance', models.IntegerField(default=0)),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.subject')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.staff')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.option5eme', verbose_name='Option')),
            ],
        ),
    ]
