# Generated by Django 5.1.1 on 2025-02-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0072_option5eme_emploitempsoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitemps',
            name='type_evenement',
            field=models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN_PARTIEL', 'Examen Partiel'), ('EXAMEN_FINAL', 'Examen Final'), ('RATTRAPAGE', 'Rattrapage'), ('FORMATION_MILITAIRE', 'Formation Militaire'), ('TOURNEE', 'Tournée'), ('SORTIE', 'Sortie'), ('PROJET', 'Projet'), ('VISITE_MILITAIRE', 'Visite Militaire'), ('CONFERENCE', 'Conférence'), ('VACANCES', 'VACANCES'), ('JOUR_FERIES', 'JOUR_FERIES')], default='COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='emploitempsoption',
            name='type_evenement',
            field=models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN_PARTIEL', 'Examen Partiel'), ('EXAMEN_FINAL', 'Examen Final'), ('RATTRAPAGE', 'Rattrapage'), ('FORMATION_MILITAIRE', 'Formation Militaire'), ('TOURNEE', 'Tournée'), ('SORTIE', 'Sortie'), ('PROJET', 'Projet'), ('VISITE_MILITAIRE', 'Visite Militaire'), ('CONFERENCE', 'Conférence'), ('VACANCES', 'VACANCES'), ('JOUR_FERIES', 'JOUR_FERIES')], default='COURS', max_length=20),
        ),
    ]
