# Generated by Django 5.1.1 on 2025-02-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0073_alter_emploitemps_type_evenement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitemps',
            name='type_evenement',
            field=models.CharField(choices=[('COURS', 'Cours'), ('EXAMEN_PARTIEL', 'Examen Partiel'), ('EXAMEN_FINAL', 'Examen Final'), ('RATTRAPAGE', 'Rattrapage'), ('FORMATION_MILITAIRE', 'Formation Militaire'), ('TOURNEE', 'Tournée'), ('SORTIE', 'Sortie'), ('PROJET', 'Projet'), ('VISITE_MILITAIRE', 'Visite Militaire'), ('CONFERENCE', 'Conférence'), ('VACANCES', 'VACANCES'), ('JOUR_FERIE', 'JOUR_FERIE')], default='COURS', max_length=20),
        ),
    ]
