# Generated by Django 5.1.1 on 2025-02-10 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0074_alter_emploitemps_type_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatiereOption5eme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_horaire_total', models.IntegerField(default=40, verbose_name='Volume horaire total')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject', verbose_name='Matière')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.option5eme', verbose_name='Option')),
            ],
        ),
    ]
