# Generated by Django 5.1.1 on 2025-02-10 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0075_matiereoption5eme'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiereoption5eme',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.staff', verbose_name='Professeur'),
        ),
        migrations.AlterField(
            model_name='matiereoption5eme',
            name='matiere',
            field=models.CharField(max_length=255, verbose_name='Nom de la matière'),
        ),
    ]
