# Generated by Django 5.1.1 on 2025-02-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0076_matiereoption5eme_professeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitempsoption',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.matiereoption5eme'),
        ),
    ]
