# Generated by Django 5.1.1 on 2025-02-10 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0077_alter_emploitempsoption_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitempsoption',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.matiereoption5eme', verbose_name='Matière (Option)'),
        ),
    ]
